#!/bin/bash

#/etc/init.d/oledstatus

### BEGIN INIT INFO

# Provides:oledstatus

# Required-Start:$remote_fs $syslog

# Required-Stop:$remote_fs $syslog

# Default-Start:2 3 4 5

# Default-Stop:0 1 6

# Short-Description: oled status display

# Description: This service is used to display temperature, cpu load, memory usage and ip on OLED SSD1306

### END INIT INFO


case "$1" in
    start):
        echo "START OLED_STATUS"
        export OLED_FONT=/home/pi/Workspace/oled/CollegeBlock20-K5ql.ttf
        nohup python3 /home/pi/Workspace/oled/oledshowstatus.py > /home/pi/Workspace/oled/nohup.out 2>&1 &
    ;;
    stop):
        echo "STOP OLED_STATUS"
        pid=$(ps aux | grep -m 1 'python3 /home/pi/Workspace/oled/oledshowstatus.py' | awk '{ print $2 }')
        echo "[$pid]"
        kill -9 $pid
        export OLED_FONT=
        python3 /home/pi/Workspace/oled/oledshowstatus.py clear
    ;;
    *):
        echo "Usage: service start_tool start|stop"
        exit 1
    ;;
esac

exit 0
